import uuid from 'uuid/v4';

export function getProjectsApi() {
  return new Promise( (res, rej) => {
    res(
      [
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
        {
          enterpreneur_id: 2,
          project_name: 'TES 4 Oblivion',
          project_field: 'Video Games',
          project_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique justo eget mauris posuere vestibulum. Sed tincidunt, leo ac faucibus convallis, nisl urna mollis diam, quis dapibus massa nulla sed erat. Curabitur at ipsum metus. Vivamus id ante vitae ipsum viverra aliquam eget sit amet dui. Praesent efficitur hendrerit tempus.',
          status_id: 2,
          money_to_collect: 79999.56,
          money_collected: 80000.78,
          money_invested: 2000.312,
          video_url: 'https://www.youtube.com/watch?v=mWLZ07U85h0',
          project_finish_date: '2018-10-22 00:00:00',
          min_unit_price: 10,
          min_units: 1,
          tashkif_file: '',
          project_files: [],
          project_team: [],
          id: uuid(),
        },
      ]
    )
  })
}
